trigger: none

pr:
- master
- release

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | ./pom.xml'
      path: $(MAVEN_CACHE_FOLDER)
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: mkdir -p $(MAVEN_CACHE_FOLDER); pwd; ls -al $(MAVEN_CACHE_FOLDER)
  - task: Maven@3
    env:
      JAVA_HOME_11_X64: /usr/local/openjdk-11
    inputs:
      goals: 'clean install'
      # These are Maven CLI options (and show up in the build logs) - "-nsu"=Don't update snapshots. We can remove this when Maven OSS is more healthy
      options: '-P ALLMODULES,JACOCO,CI,ERRORPRONE -e -B -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
      # These are JVM options (and don't show up in the build logs)
      mavenOptions: '-Xmx1024m $(MAVEN_OPTS) -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS -Duser.timezone=America/Toronto'
      jdkVersionOption: 1.11
  - script: bash <(curl https://codecov.io/bash) -t $(CODECOV_TOKEN)
    displayName: 'codecov'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: $(System.DefaultWorkingDirectory)/hapi-fhir-jacoco/target/site/jacoco-report/jacoco.xml
      reportDirectory: $(System.DefaultWorkingDirectory)/hapi-fhir-jacoco/target/site/jacoco-report/
      failIfCoverageEmpty: false
